[package]
name = "chiptool"
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.1.6", features = ["derive"] }
env_logger = "0.9.0"
inflections = "1.1"
log = { version = "~0.4", features = ["std"] }
quote = "1.0"
proc-macro2 = "1.0"
anyhow = "1.0.19"
regex = "1.4.3"
serde = { version = "1.0.123", features = [ "derive" ]}
serde_yaml = "0.8.15"
svd-parser = { version = "0.10.2", features = ["derive-from"] }
